spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NEW
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    web: debug
    swagger: debug